version: 0.2

phases:
  build:
    commands:
      - echo "Starting EC2 instance creation using CloudFormation..."
      - aws cloudformation create-stack --stack-name MyEC2Stack --template-body file://ec2.yaml --parameters ParameterKey=KeyName,ParameterValue=aws_tony_use1 ParameterKey=InstanceType,ParameterValue=t2.micro
      - echo "Waiting for stack creation to complete..."
      - aws cloudformation wait stack-create-complete --stack-name MyEC2Stack
      - echo "EC2 instance created successfully."