AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS CI/CD pipeline demo using GitHub + CodePipeline + CodeBuild + Docker + ECR.
  Includes reading GitHub PAT securely from SSM Parameter Store (SecureString).

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub user or organization owning the repository.

  GitHubRepo:
    Type: String
    Description: GitHub repository name.

  GitHubBranch:
    Type: String
    Default: main
    Description: Git branch that will trigger the pipeline.

  # IMPORTANT:
  # This parameter is the *key name* of the SSM SecureString parameter.
  # Example value: /github/pat/pipeline
  GitHubOAuthToken:
    Type: String
    Default: /github/pat/pipeline
    Description: SSM SecureString parameter key storing the GitHub PAT.

  EcrRepositoryUri:
    Type: String
    Description: Existing ECR repository URI where Docker images will be pushed.

  CodeBuildImage:
    Type: String
    Default: "aws/codebuild/standard:7.0"
    Description: CodeBuild environment image used for building Docker images.


Resources:
  ###########################################
  # S3 ARTIFACT BUCKET
  ###########################################
  # CodePipeline requires an S3 bucket to store
  # source and build artifacts.
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256


  ###########################################
  # IAM ROLE FOR CODEBUILD
  ###########################################
  # Allows CodeBuild to:
  #  - Access S3 bucket
  #  - Authenticate & push images to ECR
  #  - (Optional) create ENI if needed
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "CodeBuildRole-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Allow CodeBuild to interact with S3 artifact bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub "${ArtifactBucket.Arn}/*"

              # Allow pushing Docker images to ECR
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:DescribeRepositories
                  - ecr:BatchGetImage
                Resource: "*"

              # Needed if build runs inside VPC (optional)
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: "*"


  ###########################################
  # CODEBUILD PROJECT
  ###########################################
  # Builds the Docker image using buildspec.yml
  # and pushes it to ECR.
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "docker-build-${AWS::StackName}"
      Description: Build and push Docker image to ECR.
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        PrivilegedMode: true   # Required for Docker build
        EnvironmentVariables:
          - Name: ECR_REPO_URI
            Type: PLAINTEXT
            Value: !Ref EcrRepositoryUri
      Source:
        Type: CODEPIPELINE
        BuildSpec: "buildspec.yml"
      TimeoutInMinutes: 30


  ###########################################
  # IAM ROLE FOR CODEPIPELINE
  ###########################################
  # Allows CodePipeline to:
  #  - Read/write artifacts from S3
  #  - Trigger CodeBuild
  #  - Use dynamic SSM SecureString reference
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "CodePipelineRole-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Allow CodePipeline to use S3 artifact bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub "${ArtifactBucket.Arn}/*"

              # Allow CodePipeline to start CodeBuild project
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: !GetAtt CodeBuildProject.Arn

              # Allow CodePipeline to pass IAM role to CodeBuild
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !GetAtt CodeBuildRole.Arn


  ###########################################
  # CODEPIPELINE
  ###########################################
  # Main CI/CD pipeline:
  #   Stage 1: Source from GitHub
  #   Stage 2: Build using CodeBuild
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "aws-cicd-docker-pipeline-${AWS::StackName}"
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket

      Stages:
        ###################################
        # SOURCE STAGE (GitHub)
        ###################################
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                # Read GitHub PAT securely using SSM dynamic reference
                OAuthToken: !Sub "{{resolve:ssm-secure:${GitHubOAuthToken}}}"
                PollForSourceChanges: "false"
              RunOrder: 1

        ###################################
        # BUILD STAGE (CodeBuild)
        ###################################
        - Name: Build
          Actions:
            - Name: CodeBuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1


  ###########################################
  # GITHUB WEBHOOK (Triggers Pipeline)
  ###########################################
  # Automatically triggers CodePipeline when someone pushes to GitHub.
  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Name: !Sub "github-webhook-${AWS::StackName}"
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        # Secure GitHub Webhook secret token (from SSM)
        SecretToken: !Sub "{{resolve:ssm-secure:${GitHubOAuthToken}}}"
      Filters:
        # Only trigger on pushes to the configured branch
        - JsonPath: $.ref
          MatchEquals: !Sub "refs/heads/${GitHubBranch}"
      TargetPipeline: !Ref CodePipeline
      TargetAction: GitHubSource
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true


Outputs:
  PipelineName:
    Description: Name of the created CodePipeline.
    Value: !Ref CodePipeline

  ArtifactBucketName:
    Description: S3 bucket name where artifacts are stored.
    Value: !Ref ArtifactBucket
